version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: greens_prm
      POSTGRES_USER: greens
      POSTGRES_PASSWORD: greens
    ports: ["5432:5432"]
    healthcheck: {test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"], interval: 5s, timeout: 5s, retries: 20}

  redis:
    image: redis:7
    ports: ["6379:6379"]
    healthcheck: {test: ["CMD", "redis-cli", "ping"], interval: 5s, timeout: 5s, retries: 20}
