# Generated by Django 5.2.5 on 2025-08-21 13:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_assignment_historicalappointment_historicaldeal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVisitReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('visit_number', models.CharField(choices=[('1a', '1ª visita'), ('2a', '2ª visita'), ('3a+', '3ª ou mais')], default='1a', max_length=10, verbose_name='Número da visita')),
                ('mode', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto')], default='presencial', max_length=20, verbose_name='Tipo de visita')),
                ('objective', models.CharField(max_length=200, verbose_name='Objetivo da visita')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo do encontro')),
                ('outcome', models.TextField(blank=True, verbose_name='Resultados / decisões')),
                ('next_steps', models.TextField(blank=True, verbose_name='Próximos passos')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appointment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.appointment', verbose_name='Consulta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical visit report',
                'verbose_name_plural': 'historical visit reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
